---
# The below config turns on/off the auto inv capability (OPTIONS: on and off)
auto-inv: "on"

# The below config turns on/off the auto smelt capability (OPTIONS: on and off)
auto-smelt: "on"

# The below config is the message that is sent when your inventory is full (NOTE: Use & for color coding)
inv-full-message: "&cYour inventory is full"

# The below config turns on payment for when you use auto smelt (OPTIONS: on and off)
economy: "off"

# The below config is the price you pay when you smelt (NOTE: economy option must be on for this to work)
auto-smelt-price: 100
...